version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-chat
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_password
      POSTGRES_DB: chat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: mongodb-chat
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chat_app
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: ms_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
